language: node_js
node_js:
- 8
script: npm run clean & npm run lint && npm i && npm run build
deploy:
  provider: npm
  email: ackeedevelopment@gmail.com
  skip_cleanup: true
  api_key:
    secure: muSHO1dkf/TkaHdRz180jtzvzZbtzxctWGk008QdChmmYk0N3HRwa0eCNCvxMTBMonIpf7a+FEWiWJxjLvLiDIYjPTkb/xiDC9ZvCqhiBUlMl4qCNEcp1IwuD4yEbq8zpbHoqAZxN94FZBsBLqL2NxTxWKyhQPVJiEa1RNUBzA2uHS6UicRps3biY2IOLIgx3QYR9/1nxKV0NrFltZhy3K5CnQu4AQwmV+hWGVIrxyDl+Sj7/B2SGXrZXrvOWJnkuP6pP4KgFTGh8VrA8Sjl++3Ql/3w0IJUDA54UK5AwE1PFitkwO0n4dfIJbFxJJyq/QW+ZDuac9oD/nv0vEVa52438tbrNgJU50wHYpRCgWFg/KtqghZRXgTEvsv5nqg6zaFfjlfyLV+mU1gPwaosGMoPS4084e8yDquXcuzYkaiOWEqAYaTWy793waQDocJ8vc02lkjR09OIw0m5JyeF0R+BLNSD7eilrbanKJQaE8320mAgc5aIQvx+aUtZHb5GuBbp5MMjMRAJRC6UitNUj1eSIW3VhL8C2A1RSzP3fhRAKn3GnbtbBTQGNsgadJ4bHi15DxQP2qiJ323gkdQ0ai2oAuAlgNPcz6P8PAU9yP1L8rLLKmOk86CKCKJtiSqTNSc3PVnBcvy6Nq6FNMfBjMnTDn+TCxKb0cYYC7uGMHY=
  on:
    tags: true
    repo: AckeeCZ/jerome
